name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Display Go version
        run: gilded-rose go test -v ./...
      - name: Run tests
        run: docker run -v .:/usr/src/app gilded-rose go test -v ./...

