name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t gilded-rose .
      - name: Run tests
        run: docker run -v .:/usr/src/app gilded-rose go test -v ./...

